# Generated by Django 3.1.4 on 2021-01-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210121_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/images/profile1.png', null=True, upload_to=''),
        ),
    ]
